fileGroups:
  changesets:
    - '/.changeset/config.json'
  release:
    - 'package.json'

tasks:
  prepare:
    type: build
    description: 'Pulls the project to build an artifact'
    deps:
      - target: '~:build'
        optional: true
    options:
      runInCI: false
      internal: true
    inputs:
      - '@group(sources)'
      - '@group(configs)'
      - '@group(changesets)'

  version:
    type: build
    description: 'Consumes changes and updates entries to the according semver bump'
    command: 'changeset version'
    deps:
      - '~:prepare'
    options:
      runInCI: false
    inputs:
      - '@group(sources)'
      - '@group(configs)'
      - '@group(changesets)'

  publish:
    type: run
    description: 'Publishes the artifact to configured mediums'
    command: 'changeset publish'
    deps:
      - '~:version'
    options:
      runInCI: false
    inputs:
      - '@group(outputs)'
      - '@group(changesets)'
