tasks:
  format:
    type: test
    description: 'Runs prettier without writing/formatting unstyled input.'
    command: 'prettier'
    args:
      - '--check'
      - '--cache'
      - '--cache-location=./.prettiercache'
      - '--no-error-on-unmatched-pattern'
      - '.'
    inputs:
      - '@group(sources)'
      - '@group(configs)'
      - '@group(tests)'
    outputs:
      - '.prettiercache'
  format-write:
    extends: 'format'
    args: '--write'
    options:
      runInCI: false
