packages:
  - 'apps/**'
  - 'libs/**'

catalogs:
  nest:
    "@nestjs/common": 11.1.13
    "@nestjs/core": 11.1.13
    "@nestjs/testing": 11.1.13

    "@nestjs/platform-express": 11.1.13
    
    "@nestjs/cli": 11.0.16
    "@nestjs/schematics": 11.0.9

  nest-libs:
    "nest-typed-config": 2.10.1

    "@ogma/common": 1.2.0
    "@ogma/nestjs-module": 5.5.1
    "@ogma/styler": 1.1.0

  swc:
    "@swc/cli": 0.8.0
    "@swc/core": 1.15.11

  environment:
    "@types/express": 5.0.6
    "@types/node": 24.10.13
    "@types/jest": 30.0.0

  code-quality:
    "eslint": 9.39.2
    "prettier": 3.8.1

    "@eslint/compat": 2.0.2
    "@eslint/js": 9.39.2

    "typescript-eslint": 8.56.0
    "@typescript-eslint/parser": 8.56.0
    "eslint-import-resolver-typescript": 4.4.4

    "eslint-config-prettier": 10.1.8
    
    "eslint-plugin-import-x": 4.16.1
    "eslint-plugin-svelte": 3.15.0
    
    "globals": 17.3.0

  libraries:
    "rxjs": 7.8.2
    "class-transformer": 0.5.1
    "class-validator": 0.14.3

  utilities:
    "tsconfig-paths": 4.2.0
    "reflect-metadata": 0.2.2
    "source-map-support": 0.5.21

  build-tooling:
    "typescript": 5.9.3
    "ts-loader": 9.5.4
    "ts-node": 10.9.2
    "@changesets/cli": 2.29.8
    "conventional-changelog-conventionalcommits": 9.1.0
    "@commitlint/cli": 20.4.1
    "@commitlint/config-angular": 20.4.1

  jest:
    "jest": 30.2.0

  test-tooling:
    "ts-jest": 29.4.6

  discord:
    "necord": "^6.12.4"
    "discord.js": "^14.25.1"
    "discord-api-types": "^0.38.39"