packages:
  - 'apps/**'
  - 'libs/**'

catalogs:
  nest:
    "@nestjs/common": 11.1.6
    "@nestjs/core": 11.1.6
    "@nestjs/testing": 11.1.6

    "@nestjs/platform-express": 11.1.6
    
    "@nestjs/cli": 11.0.10
    "@nestjs/schematics": 11.0.7

  nest-libs:
    "nest-typed-config": 2.10.1

    "@ogma/common": 1.2.0
    "@ogma/nestjs-module": 5.5.0
    "@ogma/styler": 1.1.0

  swc:
    "@swc/cli": 0.7.8
    "@swc/core": 1.13.5

  environment:
    "@types/express": 5.0.3
    "@types/node": 24.3.1
    "@types/jest": 30.0.0

  code-quality:
    "eslint": 9.35.0
    "prettier": 3.6.2

    "@eslint/compat": 1.3.2
    "@eslint/js": 9.35.0

    "typescript-eslint": 8.42.0
    "@typescript-eslint/parser": 8.42.0
    "eslint-import-resolver-typescript": 4.4.4

    "eslint-config-prettier": 10.1.8
    
    "eslint-plugin-import-x": 4.16.1
    "eslint-plugin-svelte": 3.12.2
    
    "globals": 16.3.0

  libraries:
    "rxjs": 7.8.2
    "class-transformer": 0.5.1
    "class-validator": 0.14.2

  utilities:
    "tsconfig-paths": 4.2.0
    "reflect-metadata": 0.2.2
    "source-map-support": 0.5.21

  build-tooling:
    "typescript": 5.9.2
    "ts-loader": 9.5.4
    "ts-node": 10.9.2
    "semantic-release": 24.2.7
    "semantic-release-monorepo": 8.0.2
    "@anolilab/semantic-release-pnpm": 2.0.3
    "@semantic-release/changelog": 6.0.3
    "@semantic-release/commit-analyzer": 13.0.1
    "@semantic-release/git": 10.0.1
    "@semantic-release/github": 11.0.5
    "@semantic-release/release-notes-generator": 14.1.0
    "conventional-changelog-conventionalcommits": 9.1.0
    "@commitlint/cli": 19.8.1
    "@commitlint/config-angular": 19.8.1
    "tsdown": 0.14.2

  jest:
    "jest": 30.1.3

  test-tooling:
    "ts-jest": 29.4.1

  discord:
    "necord": "^6.11.1"
    "discord.js": "^14.22.1"
    "discord-api-types": "^0.38.24"