packages:
  - 'apps/**'
  - 'libs/**'

catalogs:
  nest:
    "@nestjs/common": 11.1.6
    "@nestjs/core": 11.1.6
    "@nestjs/testing": 11.1.6

    "@nestjs/platform-express": 11.1.6
    
    "@nestjs/cli": 11.0.10
    "@nestjs/schematics": 11.0.8

  nest-libs:
    "nest-typed-config": 2.10.1

    "@ogma/common": 1.2.0
    "@ogma/nestjs-module": 5.5.1
    "@ogma/styler": 1.1.0

  swc:
    "@swc/cli": 0.7.9
    "@swc/core": 1.13.21

  environment:
    "@types/express": 5.0.3
    "@types/node": 24.6.2
    "@types/jest": 30.0.0

  code-quality:
    "eslint": 9.37.0
    "prettier": 3.6.2

    "@eslint/compat": 1.4.0
    "@eslint/js": 9.37.0

    "typescript-eslint": 8.45.0
    "@typescript-eslint/parser": 8.45.0
    "eslint-import-resolver-typescript": 4.4.4

    "eslint-config-prettier": 10.1.8
    
    "eslint-plugin-import-x": 4.16.1
    "eslint-plugin-svelte": 3.12.4
    
    "globals": 16.4.0

  libraries:
    "rxjs": 7.8.2
    "class-transformer": 0.5.1
    "class-validator": 0.14.2

  utilities:
    "tsconfig-paths": 4.2.0
    "reflect-metadata": 0.2.2
    "source-map-support": 0.5.21

  build-tooling:
    "typescript": 5.9.3
    "ts-loader": 9.5.4
    "ts-node": 10.9.2
    "@changesets/cli": 2.29.7
    "conventional-changelog-conventionalcommits": 9.1.0
    "@commitlint/cli": 20.2.0
    "@commitlint/config-angular": 20.2.0

  jest:
    "jest": 30.2.0

  test-tooling:
    "ts-jest": 29.4.4

  discord:
    "necord": "^6.11.2"
    "discord.js": "^14.25.1"
    "discord-api-types": "^0.38.37"