packages:
  - 'apps/**'
  - 'libs/**'

catalogs:
  nest:
    "@nestjs/common": 11.1.18
    "@nestjs/core": 11.1.18
    "@nestjs/testing": 11.1.18

    "@nestjs/platform-express": 11.1.18
    
    "@nestjs/cli": 11.0.17
    "@nestjs/schematics": 11.0.10

  nest-libs:
    "nest-typed-config": 2.10.1

    "@ogma/common": 1.2.0
    "@ogma/nestjs-module": 5.5.2
    "@ogma/styler": 1.1.0

  swc:
    "@swc/cli": 0.8.1
    "@swc/core": 1.15.21

  environment:
    "@types/express": 5.0.6
    "@types/node": 24.12.2
    "@types/jest": 30.0.0

  code-quality:
    "eslint": 10.1.0
    "prettier": 3.8.1

    "@eslint/compat": 2.0.3
    "@eslint/js": 10.0.1

    "typescript-eslint": 8.57.2
    "@typescript-eslint/parser": 8.57.2
    "eslint-import-resolver-typescript": 4.4.4

    "eslint-config-prettier": 10.1.8
    
    "eslint-plugin-import-x": 4.16.2
    "eslint-plugin-svelte": 3.16.0
    
    "globals": 17.4.0

  libraries:
    "rxjs": 7.8.2
    "class-transformer": 0.5.1
    "class-validator": 0.15.1

  utilities:
    "tsconfig-paths": 4.2.0
    "reflect-metadata": 0.2.2
    "source-map-support": 0.5.21

  build-tooling:
    "typescript": 6.0.2
    "ts-loader": 9.5.7
    "ts-node": 10.9.2
    "@changesets/cli": 2.30.0
    "conventional-changelog-conventionalcommits": 9.3.1
    "@commitlint/cli": 20.5.0
    "@commitlint/config-angular": 20.5.0

  jest:
    "jest": 30.3.0

  test-tooling:
    "ts-jest": 29.4.9

  discord:
    "necord": "^6.12.4"
    "discord.js": "^14.26.2"
    "discord-api-types": "^0.38.44"