inheritedBy:
  tag: svelte

tasks:
  typecheck:
    type: test
    preset: server
    description: Runs svelte check
    command: svelte-check --tsconfig ./tsconfig.json
    deps:
      - ~:sync
    inputs:
      - '@group(configs)'
      - '@group(sources)'
      - '@group(tests)'