inheritedBy:
  toolchain: javascript

implicitDeps:
  - target: ^:build
    optional: true

implicitInputs:
  - '@group(configs)'
  - '@group(sources)'

fileGroups:
  sources:
    - src/**/*.js
    - src/**/*.d.ts
  configs:
    - package.json
    - /package.json
    - /pnpm-workspace.yaml
  outputs:
    - dist/**/*
    - mts/**/*
    - cjs/**/*
