implicitDeps:
  - target: '^:build'
    optional: true

implicitInputs:
  - '@group(configs)'
  - '@group(sources)'
  - '/tsconfig.json'
  - '/tsconfig.options.json'

fileGroups:
  sources:
    - 'src/**/*.ts'
    - '!src/**/*.spec.ts'
  configs:
    - 'package.json'
    - 'tsconfig.json'
    - 'tsconfig.options.json'
    - 'tsconfig.{build,spec}.json'
    - '*.config.{j,t}s'
    - '/pnpm-workspace.yaml'
  tests:
    - 'src/**/*.ts'
    - 'src/**/*.spec.ts'
    - 'tests/**/*.ts'
  outputs:
    - 'dist/**/*'
    - 'mts/**/*'
    - 'cjs/**/*'
    - '*.tsbuildinfo'

tasks:
  typecheck:
    type: build
    command: 'tsc'
    args:
      - '--build'
      - '--pretty'
      - '--verbose'
    inputs:
      - '@group(sources)'
      - '@group(configs)'
    outputs:
      - '@group(outputs)'
