implicitDeps:
  - '^:build'

implicitInputs:
  - '@group(configs)'
  - '@group(sources)'
  - '/tsconfig.json'
  - '/tsconfig.options.json'

fileGroups:
  sources:
    - 'src/**/*.ts'
    - '!src/**/*.spec.ts'
  configs:
    - 'package.json'
    - 'tsconfig.json'
    - 'tsconfig.{build,spec}.json'
    - '*.config.{j,t}s'
    - '/pnpm-workspace.yaml'
  tests:
    - 'src/**/*.ts'
    - 'src/**/*.spec.ts'
    - 'tests/**/*.ts'
  outputs:
    - 'dist/**/*'
    - 'mts/**/*'
    - 'cjs/**/*'
    - '*.tsbuildinfo'
# tasks:
# typecheck:
# command:
#   - 'tsc'
#   # Use incremental builds with project references
#   - '--build'
#   # Always use pretty output
#   - '--pretty'
#   # Use verbose logging to see affected projects
#   - '--verbose'
#   - '--noEmit'
# inputs:
#   # Source and test files
#   - 'src/**/*'
#   - 'tests/**/*'
#   # Type declarations
#   - 'types/**/*'
#   # Project configs
#   - 'tsconfig.json'
#   - 'tsconfig.*.json'
#   # Root configs (extended from only)
#   - '/tsconfig.options.json'
# # outputs:
# #   # Matches `compilerOptions.outDir`
# #   - 'lib'
# deps:
# - '^:build'
