tasks:
  lint:
    type: test
    description: 'Runs eslint without writing/fixing fixable errors/warnings.'
    command: 'eslint'
    args:
      - '--cache'
      - '--cache-location'
      - './.eslintcache'
      - '--color'
      - '--exit-on-fatal-error'
      - '--no-error-on-unmatched-pattern'
      - '--report-unused-disable-directives'
      - '@globs(sources)'
      - '@globs(configs)'
      - '@globs(tests)'
    inputs:
      - '@group(sources)'
      - '@group(configs)'
      - '@group(tests)'
    outputs:
      - '.eslintcache'
  lint-fix:
    extends: 'lint'
    args: '--fix'
    options:
      runInCI: false
