import { ClientEvents } from 'discord.js';

import {
	channelCreate,
	channelDelete,
	channelPinsUpdate,
	channelUpdate,
	guildAvailable,
	guildMemberAvailable,
	guildMembersChunk,
	guildUnavailable,
	messageCreate,
	messageDelete,
	messageDeleteBulk,
	messagePollVoteAdd,
	messagePollVoteRemove,
	messageReactionAdd,
	messageReactionRemove,
	messageReactionRemoveAll,
	messageReactionRemoveEmoji,
	messageUpdate,
	stageInstanceCreate,
	stageInstanceDelete,
	stageInstanceUpdate,
	threadCreate,
	threadDelete,
	threadListSync,
	threadMembersUpdate,
	threadMemberUpdate,
	threadUpdate,
	typingStart,
	voiceChannelEffectSend,
	voiceStateUpdate,
	webhooksUpdate,
	webhookUpdate,
} from './events/index.js';

export const CallpointMap: {
	[Event in keyof EventCallpointMap]: (
		...args: ClientEvents[Event]
	) => EventCallpointMap[Event];
} = {
	threadCreate,
	threadDelete,
	threadUpdate,
	threadMembersUpdate,
	messageCreate,
	messageDelete,
	messageUpdate,
	messagePollVoteAdd,
	messagePollVoteRemove,
	messageReactionAdd,
	messageReactionRemove,
	messageReactionRemoveAll,
	messageReactionRemoveEmoji,
	typingStart,
	channelPinsUpdate,
	messageDeleteBulk,
	channelCreate,
	channelDelete,
	channelUpdate,
	webhooksUpdate,
	webhookUpdate,
	stageInstanceCreate,
	stageInstanceDelete,
	stageInstanceUpdate,
	voiceStateUpdate,
	voiceChannelEffectSend,
	guildAvailable,
	guildMemberAvailable,
	guildMembersChunk,
	guildUnavailable,
	threadListSync,
	threadMemberUpdate,
};
