name: CI

on:
  push:
    branches:
      - master

env:
  MOON_DEBUG: 'true'
  PROTO_DEBUG: 'true'

jobs:
  ci:
    name: CI
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      # https://moonrepo.dev/docs/guides/ci
      - name: Setup Toolchain
        uses: moonrepo/setup-toolchain@261c62cb5b0f580c7be7c8cd0f023a2e96756095 # v0.6.4
        with:
          auto-setup: true
          auto-install: true

      - name: CI-check the whole repository targets actions
        run: 'moon ci --color'

      - name: Collect/retrospect on Moon's CI Summaries
        uses: appthrust/moon-ci-retrospect@631a1e667f96e8ca893eab69f03e425f7fbfdc2b # latest release
        if: success() || failure()
