name: Release

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    outputs:
      hasChangesets: ${{ steps.changesets.outputs.hasChangesets }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Setup Toolchain
        uses: moonrepo/setup-toolchain@261c62cb5b0f580c7be7c8cd0f023a2e96756095 # v0.6.4
        with:
          auto-setup: true
          auto-install: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Release
        id: changesets
        uses: changesets/action@v1
        with:
          version: moon exec --ignore-ci-checks --summary --concurrency=1 root:version-packages
          publish: moon exec --ignore-ci-checks --summary --concurrency=1 root:publish-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Collect/retrospect on Moon's CI Summaries
        uses: appthrust/moon-ci-retrospect@631a1e667f96e8ca893eab69f03e425f7fbfdc2b # latest release
        if: success() || failure()

  update-lock:
    name: Update pnpm lockfile
    needs: release
    if: needs.release.outputs.hasChangesets == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout changeset-release branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: changeset-release/main
          token: ${{ secrets.LOCKFILE_PAT }}
          fetch-depth: 0

      - name: Setup Toolchain
        uses: moonrepo/setup-toolchain@261c62cb5b0f580c7be7c8cd0f023a2e96756095 # v0.6.4
        with:
          auto-setup: true
          auto-install: true

      - name: Update lockfile
        run: pnpm install --lockfile-only

      - name: Commit lockfile
        uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d
        with:
          commit_message: "chore(packaging): update pnpm lockfile"
          branch: changeset-release/main