name: Release

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Setup Toolchain
        uses: moonrepo/setup-toolchain@261c62cb5b0f580c7be7c8cd0f023a2e96756095 # v0.6.4
        with:
          auto-setup: true
          auto-install: true

      - name: Install dependencies
        run: pnpm install

      - name: Release
        uses: changesets/action@v1
        with:
          version: moon exec --ignore-ci-checks --summary --concurrency=1 root:version-packages && pnpm install --no-frozen-lockfile
          publish: moon exec --ignore-ci-checks --summary --concurrency=1 root:publish-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Collect/retrospect on Moon's CI Summaries
        uses: appthrust/moon-ci-retrospect@631a1e667f96e8ca893eab69f03e425f7fbfdc2b # latest release
        if: success() || failure()
